# Generated by Django 4.1.5 on 2023-02-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbdd',
            name='books',
            field=models.CharField(default='any', max_length=100),
        ),
        migrations.AddField(
            model_name='userbdd',
            name='userName',
            field=models.CharField(default='any', max_length=100),
        ),
    ]
