# Generated by Django 4.1.5 on 2023-04-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(default='photos/Pattern-BG-EXPLORE.png', upload_to=''),
        ),
    ]
